updated cnv_trio by Benjamin

diff --git a/bin/generate_project_directory b/bin/generate_project_directory
--- a/bin/generate_project_directory
+++ b/bin/generate_project_directory
@@ -19,10 +19,22 @@
 #      ├── README.md            # Project overview
 
 
-PROJECTS_DIRECTORY=/lustre09/project/6008022/All_user_common_folder/STUDY_DIRECTORY/
+PROJECTS_DIRECTORY=/lustre09/project/6008022/LAB_WORKSPACE/STUDY_DIRECTORY/
 
 # Prompt the user for the project directory name
 read -p "Enter the project directory name: " project_name
+
+# Check if empty
+if [[ -z "$project_name" ]]; then
+    echo "Error: Project name cannot be empty."
+    exit 1
+fi
+
+# Check if it contains '/'
+if [[ "$project_name" == *"/"* ]]; then
+    echo "Error: Project name cannot contain '/'."
+    exit 1
+fi
 
 # Set the full project path
 project_path="$PROJECTS_DIRECTORY/$project_name"
@@ -43,9 +55,6 @@ cat << EOF > "$readme_path"
 
 EOF
 
-# Notify the user
-
-chmod -R ug+rwx $project_path
 
 echo "Project structure created successfully!"
 echo "README.md initialized at $readme_path"
